version: '3.4'

services:
  projectmanager.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123
    ports:
      - "1433:1433"

  projectmanager.api:
    image: projectmanager-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=projectmanager.db;Database=ProjectManagerDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;
    depends_on:
      - projectmanager.db